### ISSUE TITLE
[S] 一加7标准版输入法可否适配系统振动

### ISSUE THREAD

**Issue by Awezome** [MlgmXyysd/OnePlus-Report#32]
### 必须是合理的需求建议，在下方写下你的建议，具体描述
一加7标准版输入法可否适配系统振动？目前只有Gboard支持有系统振动选项，其它输入法都是自带振动，毫无振感。

**Comment by MlgmXyysd** [comment]
这个你需要找输入法厂商反馈，并非系统问题。
