### ISSUE TITLE
[B] 输入法下方有空白条

### ISSUE THREAD

**Issue by kljjh** [MlgmXyysd/OnePlus-Report#63]
### 反馈 BUG 分类
- [ ] 使用一加手机打游戏时遇到的 BUG
- [x] 系统相关/及其他 BUG（写清类型）：
- [ ] 游戏/应用本身 BUG（其他厂商机型也会出现）

### 手机型号
OnePlus 6

### 系统版本(仅支持氢氧系统bug反馈)
- [ ] 氢OS
- [x] 氧OS

版本：OP6_O2_BETA_30

Android 版本：10

### Bug 的具体描述
开启底部全屏手势，输入法下方出现白条/黑条。上个版本无此问题

### 是否必现 
- [x] 必现
- [ ] 偶现

### Bug 相关附件（截图/录屏/log）
![Screenshot_20191020-102658](https://user-images.githubusercontent.com/29812342/67154389-3bde9980-f32e-11e9-8948-7e556855e745.jpg)

![Screenshot_20191020-104415](https://user-images.githubusercontent.com/29812342/67154381-00dc6600-f32e-11e9-9d44-898a906f3887.jpg)

**Comment by MlgmXyysd** [comment]
同一问题重复提交
