### ISSUE TITLE
[S] 通知栏音乐显示

### ISSUE THREAD

**Issue by kljjh** [MlgmXyysd/OnePlus-Report#65]
### 必须是合理的需求建议，在下方写下你的建议，具体描述
![Screenshot_20191020-110349](https://user-images.githubusercontent.com/29812342/67154407-b14a6a00-f32e-11e9-880d-44fd2e91818c.jpg)
这地方显示的也太不成比例了……感觉是杂交出来的，建议改下排版

**Comment by MlgmXyysd** [comment]
安卓10原生样式，驳回请求
