### ISSUE TITLE
[B] Google chrome和webview均不能更新

### ISSUE THREAD

**Issue by kljjh** [MlgmXyysd/OnePlus-Report#66]
### 反馈 BUG 分类
- [ ] 使用一加手机打游戏时遇到的 BUG
- [ ] 系统相关/及其他 BUG（写清类型）：
- [x] 游戏/应用本身 BUG（其他厂商机型也会出现）

### 手机型号
OnePlus 6

### 系统版本(仅支持氢氧系统bug反馈)
- [ ] 氢OS
- [x] 氧OS

版本：OP6_O2_BETA_30

Android 版本：10

### Bug 的具体描述
chrome和webview都不能更新

### 是否必现 
- [x] 必现
- [ ] 偶现

### Bug 相关附件（截图/录屏/log）
![Screenshot_20191020-105321](https://user-images.githubusercontent.com/29812342/67154422-06867b80-f32f-11e9-8652-5f03212ed396.jpg)
![Screenshot_20191020-105012](https://user-images.githubusercontent.com/29812342/67154423-09816c00-f32f-11e9-8afc-052ef53cc2ba.jpg)

**Comment by MlgmXyysd** [comment]
尝试手动安装或尝试图中解决方法，这并非系统问题
