### ISSUE TITLE
[B] 桌面标签机率消失

### ISSUE THREAD

**Issue by smallis-2018** [MlgmXyysd/OnePlus-Report#72]
### 反馈 BUG 分类
- [ ] 使用一加手机打游戏时遇到的 BUG
- [x] 系统相关/及其他 BUG（写清类型）：
一加桌面 4.3.4.200310181936.a166fec
- [ ] 游戏/应用本身 BUG（其他厂商机型也会出现）

### 手机型号
OnePlus 7

### 系统版本(仅支持氢氧系统bug反馈)
- [x] 氢OS
- [ ] 氧OS

版本：beta10

Android 版本：10

### Bug 的具体描述
桌面标签机率消失
使用Pure图标包
重启桌面标签恢复

### 是否必现 
- [ ] 必现
- [x] 偶现

### Bug 相关附件（截图/录屏/log）
![标签消失](https://user-images.githubusercontent.com/45557002/79544830-3508c780-80c2-11ea-84de-97a2857205a7.jpg)

**Comment by MlgmXyysd** [comment]
都进行过什么操作或者你认为有关系的操作？

**Comment by smallis-2018** [comment]
> 都进行过什么操作或者你认为有关系的操作？

目前只发现任意应用内上划返回桌面会有小机率出现这个问题。
上个系统版本没有发现。

**Comment by smallis-2018** [comment]
> 都进行过什么操作或者你认为有关系的操作？

目前发现一个必现方式：

1. 在应用横屏状态下（游戏，正在播放的视频），进入多任务；
2. 使用分屏，出现桌面标签消失；
3. 退出分屏，标签恢复；
4. 再次进入横屏应用，home直接返回桌面，出现桌面标签消失；

此方式和我以前遇到的触发方式好像不一样，后续再注意记录

**Comment by smallis-2018** [comment]
升级桌面后没有再现BUG
