### ISSUE TITLE
[B] 多任务界面只能通过点击空白区域退出，返回手势无效

### ISSUE THREAD

**Issue by Potat0000** [MlgmXyysd/OnePlus-Report#75]
### 反馈 BUG 分类
- [ ] 使用一加手机打游戏时遇到的 BUG
- [x] 系统相关/及其他 BUG（写清类型）：多任务、全屏手势
- [ ] 游戏/应用本身 BUG（其他厂商机型也会出现）

### 手机型号
OnePlus 8 Pro

### 系统版本(仅支持氢氧系统bug反馈)
- [ ] 氢OS
- [x] 氧OS

版本：10.5.11.IN11AA

Android 版本：10

### Bug 的具体描述
多任务界面只能通过点击空白区域退出，返回手势无效（屏幕边缘滑动不会有返回箭头，也无法通过返回手势退出多任务界面）

### 是否必现 
- [x] 必现
- [ ] 偶现

**Comment by MlgmXyysd** [comment]
请提供 Bug 相关附件

**Comment by Potat0000** [comment]
> 请提供 Bug 相关附件

该Bug无需任何附件，因为可100%复现，且复现方法十分方便
